### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by VutonDesign** [GreenBayRules/Greenbayrules.github.io#1]
Hey, This has nothing to do with this repo but issues where off on the one I needed to let you know about.

Could you possibly take this down? https://github.com/GreenBayRules/Vutondesign.github.io
(It's not showing as a fork and is an old version, feel free to fork the newer version.

**Comment by GreenBayRules** [comment]
Yeah, I did. Sorry I was going to submit a pull request

**Comment by VutonDesign** [comment]
Okay, Thank you
